/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ucpaas_hellojni_HelloJni */

#ifndef _Included_com_ucpaas_hellojni_HelloJni
#define _Included_com_ucpaas_hellojni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ucpaas_hellojni_HelloJni
 * Method:    getFromCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ucpaas_hellojni_HelloJni_getFromCString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
